### ISSUE TITLE
PATSTAT_2017a tls203_part18 corrupted file?

### ISSUE THREAD

**Issue by dportabella** [simonemainardi/load_patstat#10]
I have a problem importing the PATSTAT_2017a `tls203_part18.zip`file.
I wonder if the data is corrupted, and whether it is from PASTAT itself or from the (legal) copy I received.

Can you please execute this command and let me know if you get the same result?

In particular, the line 3077 contains the substring `the desired bund is formed. -A $ 'N < \ ~ Ny\«.4\ \ `, which seems corrupted.

```
$ unzip -p data_PATSTAT_Biblio_2017_Spring_04/tls203_part18.zip | cat -n | head -n 3078 | tail -n 3
  3076	419831085,"en","METHODS, APPARATUS, AND ARTICLES OF MANUFACTURE TO ENCODE AUXILIARY DATA INTO TEXT DATA AND METHODS, APPARATUS, AND ARTICLES OF MANUFACTURE TO OBTAIN ENCODED DATA FROM TEXT DATA Methods, apparatus, and articles of manufacture to encode auxiliary data into text data and methods, apparatus, and articles of manufacture to obtain encoded data from text data are disclosed. An example method to embed auxiliary data into text data includes selecting a portion of auxiliary data to be encoded into text data, mapping the portion of auxiliary data to a first set of one or more encoded characters representative of the portion of the auxiliary data, mapping a position of the portion of auxiliary data within the auxiliary data to a second set of one or more encoded characters representative of the portion of the auxiliary data, and generating encoded data by including the first set of encoded characters and the second set of encoded characters in the text data. 102 __ 110 -O f 100 DATABASE DATA 104 106 -108 DATA AUXILIARY AUXILIARY REQUEST DATA DATA RECEIVER ENCODER DECODER AUTHORIZED UNAUTHORIZED PARTY PARTY"
  3077	419831086,"en","A bund is formed, according to this invention, by moulding bund sections in a bund mould which may be placed on the ground to receive and consolidate material in the cross-sectional shape of the required bund. After forming a short bund section the bund mould is repositioned to form a continuation of the formed bund section, refilled to form a further bund wall section as a continuation of the previously formed bund section and this process is repeated until the desired bund is formed. -A $ 'N < \ ~ Ny\«.4\ \ \ ''''N' N 'A~\ \ & 'N*~'~~ ~'NN~NN 'K K> >\~N4 N N ' N x'\ '~ ~ ' N\N~' 'K \N.tN'7tK\. ~NQN< \'*'*' ''K-'' N'' N-> N' N' ''N N' '4"
  3078	419831088,"en","A method is provided for the wet surface treatment of titanium dioxide, in order to produce durable universal grade titanium dioxide rutile pigment with superior optical properties. The method is characterized in that, a hydrous zirconia and silica composite layer is co-precipitated at acidic pH. Then, a layer of alumina is precipitated under a range of pH required for complete precipitation above the initial composite layer. The upper pH limit of the slurry during the alumina precipitation can be well controlled to avoid any chance for dissolution or damage of the composite zirconia-silica layer formed. Zirconia-silica composite layers and alumina thus precipitated advantageously improve the competence of the layers formed over a TiO2 base and provide improved durability with superior optical performance. The total surface treatment cycle time and chemicals used are minimal compared to conventional methods. Improvements in throughput and washing efficiency are also realized."
```

**Comment by leofiore** [comment]
If you loaded your patstat database using the original usb sticks, chances are good that some of the packages are corrupted. I specifically had an issue with the `tls231_part15.zip` archive, which i was unable to extract. I ended up downloading the online version.

With every release comes a handful cheksum file. The cheksum is calcolated using sha512 algorithm. Unfortunately the original cheksum file is not a suitable input for UNIX cmdline `sha512sum` . You can use the files i put in [this gist](https://gist.github.com/leofiore/39b6d452cf423856fff1d6e321541aa9) to check your data.

**Comment by dportabella** [comment]
cool, thanks a lot!
I've verified, and all files pass the checksum!

```
$ (for f in *; do echo -n ' '; sha512sum $f; done) | tee local.shasum
$ wget -Ooriginal.shasum https://gist.githubusercontent.com/leofiore/39b6d452cf423856fff1d6e321541aa9/raw/844dec836dad9298b31eee9edc9a79d06418473e/data.shasum
$ echo >>original.shasum  # add a new line
$ diff -s local.shasum original.shasum
Files local.shasum and original.shasum are identical
```

**Comment by dportabella** [comment]
so, the problem arises when importing this file (and some others):
```
LOAD DATA LOCAL INFILE "/tmp/tls203_part18.zip.txt"
               INTO TABLE tls203_appln_abstr FIELDS TERMINATED BY ","
               OPTIONALLY ENCLOSED BY '"'
               LINES TERMINATED BY '\r\n'
               IGNORE 1 LINES
;
```
however, the problem only happens if I run this on my Mac OSX computer (both load_patstat.sh and mysql server on my Mac OSX).
it works fine if running it on our CentOS server (both load_patstat.sh and mysql server on CentOS server).
any idea?
:(

**Comment by leofiore** [comment]
Mmmh. What is your current environment?

Assuming you are using load_patstat barely over macOS, keep in mind that several commandline tools are BSD and not GNU. For example, the main script relies heavily on GNU `sed` and GNU `grep` . It could be possibile that some options or the accepted syntax of these two commands is radically different from BSD to GNU version.

Also, check your shell version. macOS comes with a very old bash version, this could potentially break a lot of stuff in modern scripts. 

Keep in mind that i'm just geussing, these scripts were tested only on linux environments (and not all of thems!), so YMMV. 

If you are using a container, well, i give up, since i don't know what kind of collateral effects can have a linux container on a macOS system.

**Comment by dportabella** [comment]
nono, it's not about the scripts. it must be something about the OS, or the mysql configuration.

for testing, I just unzipped `tls203_part18.zip` without applying none of your `sed` commands.

```
$ cd /tmp/
$ unzip /storage/tls203_part18.zip
$ mysql -vv --show-warnings --local-infile -uUSER -p -hlocalhost

mysql> use test

mysql> CREATE TABLE tls203_appln_abstr (
  appln_id int(11) NOT NULL DEFAULT '0',
  appln_abstract_lg char(2) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  appln_abstract text COLLATE utf8mb4_unicode_ci,
  PRIMARY KEY (appln_id)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci  AVG_ROW_LENGTH=800;

mysql> LOAD DATA LOCAL INFILE "/tmp/tls203_part18.txt"
               INTO TABLE tls203_appln_abstr FIELDS TERMINATED BY ","
               OPTIONALLY ENCLOSED BY '"'
               LINES TERMINATED BY '\r\n'
               IGNORE 1 LINES
;

ERROR 1300 (HY000): Invalid utf8mb4 character string: '"A bund is formed, according to this invention, by moulding bund'

exit

$ cat -n tls203_part18.txt | head -n 3077 | tail -n 1
  3077	419831086,"en","A bund is formed, according to this invention, by moulding bund sections in a bund mould which may be placed on the ground to receive and consolidate material in the cross-sectional shape of the required bund. After forming a short bund section the bund mould is repositioned to form a continuation of the formed bund section, refilled to form a further bund wall section as a continuation of the previously formed bund section and this process is repeated until the desired bund is formed. -A $ 'N < \ ~ Ny\«.4\ \ \ ''''N' N 'A~\ \ & 'N*~'~~ ~'NN~NN 'K K> >\~N4 N N ' N x'\ '~ ~ ' N\N~' 'K \N.tN'7tK\. ~NQN< \'*'*' ''K-'' N'' N-> N' N' ''N N' '4"
```

**Comment by dportabella** [comment]
It also works by running the `load_patstat.sh` script from my Mac OSX computer, and using the mysql server on our CentOS server.
so, the problem appears only when I use the mysql server on my Mac OSX computer. I am using the `my.cnf` file that you told me before.
any idea?

**Comment by leofiore** [comment]
well, this could be anything.

It could be mysql-server using different libraries for macOS in order to load documents.

But it could also be a problem with HFS+ handling differently the text files. 
Did you load the centOS mysql database using files stored in your macOS? if yes. then macOS mysql is the problem.

**Comment by dportabella** [comment]
thx. I've posted a mcve at stackoverflow: https://stackoverflow.com/questions/45370517/mysql-error-1300-hy000-invalid-utf8mb4-character-string
I close this issue here.
