### ISSUE TITLE
standardized EEE-PPAT person table and TLS221_INPADOC_PRS

### ISSUE THREAD

**Issue by dportabella** [simonemainardi/load_patstat#13]
The README.md file says:

> The utility is also capable of loading the standardized EEE-PPAT person table with harmonized assignee names and assignee sector allocations (https://www.ecoom.be/en/EEE-PPAT). This table has been officially included in version 2015a.

Is this the tls906_person table, which is already included by default in the patstat_2017a?

> TLS221_INPADOC_PRS DVD zipped table may be copied there as well.

Is this the tls231_inpadoc_legal_event table, which is already included by default in the patstat_2017a?

**Comment by simonemainardi** [comment]
I have no access to the 2017a version. @leofiore can you please comment and possibly update the readme? Thanks

**Comment by leofiore** [comment]
>Is this the tls906_person table, which is already included by default in the patstat_2017a?

You are looking for PSN_ fields in `tls906_person` and `tls206_person`. As you can see from the documentation, the EEE-PAT names are called **P**atstat **S**tandardized **N**ames.

>Is this the tls231_inpadoc_legal_event table, which is already included by default in the patstat_2017a?

Correct, the name change occurred in 2017a release.
