### ISSUE TITLE
Table tls903

### ISSUE THREAD

**Issue by dportabella** [simonemainardi/load_patstat#15]
The `tls903` file is not imported (not even in the original patstat script). Do you know if there is a reason for this? Is it possible to import it also?

```
reg_code,reg_label,up_reg_code,up_reg_label,up_reg_code_alt,up_reg_label_alt,ctry_code
"AT111","Mittelburgenland","AT11","BURGENLAND (A)","","","AT"
"AT112","Nordburgenland","AT11","BURGENLAND (A)","","","AT"
"AT113","Südburgenland","AT11","BURGENLAND (A)","","","AT"
"AT121","Mostviertel-Eisenwurzen","AT12","NIEDERÖSTERREICH","","","AT"
...
```

**Comment by simonemainardi** [comment]
that table was not available in earlier patstat versions. Feel free to send a PR. Thank you

**Comment by leofiore** [comment]
it looks to me that `tls903` table is a support table used to normalize NUTS code informations. Is not officially included in release 2017a, neither mentioned in the official documentation, so is safe to ignore it.

**Comment by dportabella** [comment]
ok, thx!
