### ISSUE TITLE
Specified key was too long when creating table tls906_person.

### ISSUE THREAD

**Issue by dportabella** [simonemainardi/load_patstat#9]
`load_patstat.sh` complains with this error:
```
CREATE TABLE tls906_person (
  person_id int(11) NOT NULL DEFAULT '0',
  person_name varchar(300) COLLATE utf8mb4_unicode_ci NOT NULL,
  person_address varchar(1000) COLLATE utf8mb4_unicode_ci NOT NULL,
  person_ctry_code char(2) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  nuts char(5) NOT NULL DEFAULT '',
  nuts_level smallint  NOT NULL DEFAULT '9',
  doc_std_name_id int(11) NOT NULL DEFAULT '0',
  doc_std_name varchar(500) COLLATE utf8mb4_unicode_ci NOT NULL,
  psn_id int(11) NOT NULL DEFAULT '0',
  psn_name varchar(500) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  psn_level tinyint(4) NOT NULL DEFAULT '0',
  psn_sector varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  han_id int(11) NOT NULL DEFAULT '0',
  han_name varchar(500) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  han_harmonized int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (person_id),
  KEY IX_ppat_person_ctry_code (person_ctry_code),
  KEY IX_ppat_nuts (nuts),
  KEY IX_ppat_psn_name (psn_name(333)),
  KEY IX_ppat_psn_sector (psn_sector),
  KEY IX_ppat_psn_id (psn_id),
  KEY IX_ppat_han_id (han_id),
  KEY IX_han_name (han_name(333)),
  KEY IX_han_harmonized (han_harmonized)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci  AVG_ROW_LENGTH=100
--------------

ERROR 1071 (42000) at line 422: Specified key was too long; max key length is 1000 bytes
Bye
```

I am running mysql version 5.7.17.

any idea?
why is it working for you?
did you configured your mysql server somehow?

**Comment by dportabella** [comment]
It works for me by replacing `ENGINE=MyISAM` by `ENGINE=InnoDB`.
However, why is it working for you?

**Comment by simonemainardi** [comment]
+@leofiore

**Comment by leofiore** [comment]
No idea. I've used mysql5.5 on ubuntu 14.04 , arch x86_64 . The relevant tweaks for our mysql configurations are these:

```
[mysqld]
collation-server = utf8_unicode_ci
character-set-server = utf8
default-storage-engine=myisam
interactive_timeout=600
wait_timeout=600

# MAINA tweaks
sort_buffer_size = 2G
read_buffer_size = 200M
read_rnd_buffer_size = 800M
myisam_sort_buffer_size = 2G
query_cache_size = 2G
query_cache_limit = 1G
key_buffer_size = 4G
bulk_insert_buffer_size = 1G
join_buffer_size = 4G
delay-key-write = ON

# LEO tweaks
tmp_table_size=1G
max_heap_table_size=1G

collation-server = utf8_unicode_ci
character-set-server = utf8
```

however none of these options looks relevant for this problem. Could it be a specific mysql version issue?

**Comment by dportabella** [comment]
I tried this config, but I get the same problem.
I will try with a docket instance.

**Comment by dportabella** [comment]
I tried with docker, both with mysql 5.5 and in 5.7.19, and yes,
it seems that it works on mysql 5.5, but not in mysql 5.7.19.

if you want to try yourself, this is how to install and run mysql client with docker:
```
docker run --name some-mysql -e MYSQL_ROOT_PASSWORD=my-secret-pw -d mysql:5.5
docker run -it --link some-mysql:mysql --rm mysql sh -c 'exec mysql -h"$MYSQL_PORT_3306_TCP_ADDR" -P"$MYSQL_PORT_3306_TCP_PORT" -uroot -p"$MYSQL_ENV_MYSQL_ROOT_PASSWORD"'
```

**Comment by dportabella** [comment]
It seems that mysql suggests to use InnoDB engine (instead of MyISAM) since version 5.7+:
https://dev.mysql.com/doc/refman/5.7/en/innodb-introduction.html

Also, the max key length is 3072 bytes in InnoDB (instead of 1000 bytes in MyISAM).

In order to do so, we need to change `MyISAM` by `InnoDB` in `create_schema.sh`,
but also the `myisamchk *.MYI` commands used in `load_patstat.sh`.

**Comment by simonemainardi** [comment]
In a non-transactional database such as patstat I believe MyISAM is still the preferred engine as it is simpler and faster when ACIDidity  is not necessary.

**Comment by leofiore** [comment]
without a proper benchmark i have to agree with @simonemainardi about using MyISAM format, which also have an advantage (at least for my purposes) in terms of tables import/export.

BTW, i would consider to add a new feature in order to select the preferred engine, thus modifying the `create_schema.sh` script in order to make the engine option parametric, i.e. using `ENGINE=${PREFERRED_ENGINE}` or something like this. This parameter should be also added as an option for `load_patstat.sh`. It could be useful in order to use also different engines on different rdbms, like XtraDB on mariadb.

**Comment by dportabella** [comment]
I see. but the current schema does not work with MyISAM on the latest mysql version (5.7+).
```ERROR 1071 (42000) at line 422: Specified key was too long; max key length is 1000 bytes```

**Comment by leofiore** [comment]
But it does on 5.5, so it's perfectly logical IMO to let the user decide based on which is his preferred engine. In order to have a more secure environment we could check mysql version before starting the creation phase and ask the user to abort/continue the current process with the selected options.

**Comment by dportabella** [comment]
I just run the full script on mysql 5.5, and it seems that MySQL 5.5 does not support key length > 1000 bytes on MyISAM neither. The different is that mysql 5.5 only shows a warning (meaning that it didn't work, but it skips the error), while 5.7 throws an error.

```
CREATE TABLE tls906_person (
  person_id int(11) NOT NULL DEFAULT '0',
  person_name varchar(300) COLLATE utf8mb4_unicode_ci NOT NULL,
  person_address varchar(1000) COLLATE utf8mb4_unicode_ci NOT NULL,
  person_ctry_code char(2) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  nuts char(5) NOT NULL DEFAULT '',
  nuts_level smallint  NOT NULL DEFAULT '9',
  doc_std_name_id int(11) NOT NULL DEFAULT '0',
  doc_std_name varchar(500) COLLATE utf8mb4_unicode_ci NOT NULL,
  psn_id int(11) NOT NULL DEFAULT '0',
  psn_name varchar(500) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  psn_level tinyint(4) NOT NULL DEFAULT '0',
  psn_sector varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  han_id int(11) NOT NULL DEFAULT '0',
  han_name varchar(500) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  han_harmonized int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (person_id),
  KEY IX_ppat_person_ctry_code (person_ctry_code),
  KEY IX_ppat_nuts (nuts),
  KEY IX_ppat_psn_name (psn_name(333)),
  KEY IX_ppat_psn_sector (psn_sector),
  KEY IX_ppat_psn_id (psn_id),
  KEY IX_ppat_han_id (han_id),
  KEY IX_han_name (han_name(333)),
  KEY IX_han_harmonized (han_harmonized)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci  AVG_ROW_LENGTH=100
--------------

Query OK, 0 rows affected, 2 warnings

Warning (Code 1071): Specified key was too long; max key length is 1000 bytes
Warning (Code 1071): Specified key was too long; max key length is 1000 bytes
```

**Comment by simonemainardi** [comment]
try to reduce key lengths for psn_name and han_name from 333 down to 255. This is the worst case as utf8mb4 takes at most 4 bytes per character

**Comment by simonemainardi** [comment]
any news here?

**Comment by dportabella** [comment]
I tried, but 255 is still too long. 255*4 = 1020. max is 1000.
I tried with 250 and it works.

**Comment by simonemainardi** [comment]
yes, sorry I meant 250. Thank you.
